### PR TITLE
support branch  release-2.4

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: root <daliu@redhat.com>

### CODE REVIEW

**Comment by ldpliu** [comment]
@jnpacker I use  [supported-ocp-versions.json](https://github.com/open-cluster-management/acm-hive-openshift-releases/blob/b3a458179026877ad3dbd0ca9347f03232bf2a57/supported-ocp-versions.json) file to maintain the supported version, and then generate different clusterimageset file based on it.  Please review the change. 
(It looks like YangLe and I still can not merge the cde, the ci show `Not mergeable. Merge type "squash" disallowed by repo settings `, you may need to config the squash merge in repo setting.)

**Comment by ldpliu** [comment]
https://github.com/open-cluster-management/backlog/issues/17691

**Review by jnpacker — COMMENTED** [review]
lgtm

**Pull request merged**
